version: '3.8'

services:
  node-a:
    build: .
    image: raft-node-base
    container_name: raft-node-a
    command: ["-Dexec.args=A"]
    ports:
      - "8081:8081"

  node-b:
    image: raft-node-base
    container_name: raft-node-b
    command: ["-Dexec.args=B"]
    ports:
      - "8082:8082"

  node-c:
    image: raft-node-base
    container_name: raft-node-c
    command: ["-Dexec.args=C"]
    ports:
      - "8083:8083"